<footer class="footer navbar-dark bg-dark">
    <div class="container-fluid">
        <span class="text-muted">Generated by ${reportDetails.generatorName}, ${reportDetails.date}.</span>
    </div>
</footer>